# Hi - Kod Atölyesi Numpy Task

##  Exercise 1
- Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

<p>Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.</p>

In [1]:
import numpy as np
import pandas as pd

a = np.array([2,3,4,5,8,7], dtype = "int64")
a

array([2, 3, 4, 5, 8, 7], dtype=int64)

In [3]:
a.size

6

## Exercise 2
- Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

In [6]:
b = np.array([[1,2,6,7], [4,3,9,5]])
c = np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])

In [8]:
b.size

8

In [10]:
c.size

12

In [12]:
b.shape

(2, 4)

In [14]:
c.shape

(2, 2, 3)

In [16]:
b

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [18]:
c

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

## Exercise 3
- İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [37]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
b[0][1]

2

In [40]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
b[0][3]

7

In [48]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
c[1][1][2]

9

In [53]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
c[0][0][1]

5

## Exercise 4 
- Arrayler üzerinde slicing işlemi uygulayalım.

In [58]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
b[0][1:3]

array([2, 6])

In [63]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
b[1][1:4]

array([3, 9, 5])

In [69]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
c[0][1]

array([21,  8, 11])

In [75]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
c[1][0][1:3]

array([ 6, 20])

## Exercise 5
- 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [77]:
# 5x3 boyutunda sıfırlardan oluşan array
array_sifir = np.zeros((5, 3), dtype=int)

# 5x3 boyutunda birlerden oluşan array
array_bir = np.ones((5, 3), dtype=int)

# Satır bazında birleştirme (vertikal)
satir_birlesim = np.vstack((array_sifir, array_bir))

# Sütun bazında birleştirme (horizontal)
sutun_birlesim = np.hstack((array_sifir, array_bir))

In [79]:
satir_birlesim

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [81]:
sutun_birlesim

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])